const INDENT = '  ';

function indent(lines) {
  return lines.map((line) => `${INDENT}${line}`);
}

function statementToLines(block) {
  const lines = [];
  let current = block;

  while (current) {
    if (current.type === 'robocode_set_builtin_led') {
      const state = current.getFieldValue('STATE') === 'ON' ? 'HIGH' : 'LOW';
      lines.push(`digitalWrite(LED_BUILTIN, ${state});`);
    } else if (current.type === 'robocode_wait_ms') {
      const milliseconds = Number(current.getFieldValue('MILLISECONDS'));
      lines.push(`delay(${Number.isFinite(milliseconds) ? milliseconds : 0});`);
    }
    current = current.getNextBlock();
  }

  return lines;
}

export function generateArduinoCode(workspace) {
  const startBlocks = workspace.getTopBlocks(true).filter((block) => block.type === 'robocode_start');
  const body = startBlocks.flatMap((block) => statementToLines(block.getInputTargetBlock('DO')));
  const loopBody = body.length ? body : ['// Drag LED and wait blocks into START.'];

  return [
    '// Generated by RoboCode Phase 1 — do not edit this file by hand.',
    '#include <Arduino.h>',
    '',
    'void setup() {',
    `${INDENT}pinMode(LED_BUILTIN, OUTPUT);`,
    '}',
    '',
    'void loop() {',
    ...indent(loopBody),
    '}',
    '',
  ].join('\n');
}
