const INDENT = '  ';

function indent(lines) {
  return lines.map((line) => `${INDENT}${line}`);
}

function statementToLines(block) {
  const lines = [];
  let current = block;

  while (current) {
    if (current.type === 'robocode_set_builtin_led') {
      const state = current.getFieldValue('STATE') === 'ON' ? 'HIGH' : 'LOW';
      lines.push(`digitalWrite(ROBOCODE_BUILT_IN_LED_PIN, ${state});`);
    } else if (current.type === 'robocode_wait_ms') {
      const milliseconds = Number(current.getFieldValue('MILLISECONDS'));
      lines.push(`delay(${Number.isFinite(milliseconds) ? milliseconds : 0});`);
    }
    current = current.getNextBlock();
  }

  return lines;
}

export function generateArduinoCode(workspace) {
  const startBlocks = workspace.getTopBlocks(true).filter((block) => block.type === 'robocode_start');
  const body = startBlocks.flatMap((block) => statementToLines(block.getInputTargetBlock('DO')));
  const usesBuiltInLed = body.some((line) => line.includes('ROBOCODE_BUILT_IN_LED_PIN'));
  const setupBody = usesBuiltInLed
    ? [`${INDENT}pinMode(ROBOCODE_BUILT_IN_LED_PIN, OUTPUT);`]
    : [];

  return [
    '// Generated by RoboCode Phase 1 — do not edit this file by hand.',
    '#include <Arduino.h>',
    ...(usesBuiltInLed ? ['', 'constexpr uint8_t ROBOCODE_BUILT_IN_LED_PIN = 2;'] : []),
    '',
    'void setup() {',
    ...setupBody,
    '}',
    '',
    'void loop() {',
    ...indent(body),
    '}',
    '',
  ].join('\n');
}
