// Generated by RoboCode Phase 1 — do not edit this file by hand.
#include <Arduino.h>

constexpr uint8_t ROBOCODE_BUILT_IN_LED_PIN = 2;

void setup() {
  pinMode(ROBOCODE_BUILT_IN_LED_PIN, OUTPUT);
}

void loop() {
  digitalWrite(ROBOCODE_BUILT_IN_LED_PIN, HIGH);
  delay(1000);
  digitalWrite(ROBOCODE_BUILT_IN_LED_PIN, LOW);
  delay(1000);
}
